# Generated by Django 2.2 on 2019-05-06 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electric_points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_status', models.CharField(choices=[('0', 'A instalar'), ('1', 'A energizar'), ('2', 'A comissionar'), ('3', 'A operar'), ('4', 'Concluído')], default='0', max_length=255, verbose_name='Etapa de referência')),
                ('description', models.TextField(null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrada em')),
                ('solved', models.BooleanField(default=False, verbose_name='Solucionada')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrada por')),
            ],
            options={
                'verbose_name': 'Pendência',
                'verbose_name_plural': 'Pendências',
                'db_table': 'pendencies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_status', models.CharField(choices=[('0', 'A instalar'), ('1', 'A energizar'), ('2', 'A comissionar'), ('3', 'A operar'), ('4', 'Concluído')], default='0', max_length=255, verbose_name='Etapa de referência')),
                ('sob', models.CharField(max_length=255, null=True, unique=True, verbose_name='SOB')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('finished_at', models.DateTimeField(blank=True, verbose_name='Data de conclusão')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_status', models.CharField(choices=[('0', 'A instalar'), ('1', 'A energizar'), ('2', 'A comissionar'), ('3', 'A operar'), ('4', 'Concluído')], max_length=255, verbose_name='Etapa de referência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('programmed_date', models.DateTimeField(null=True, verbose_name='Data programada')),
                ('real_date', models.DateTimeField(null=True, verbose_name='Data de realização')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_project', to='projects.Projects', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'db_table': 'steps',
            },
        ),
        migrations.AddField(
            model_name='projects',
            name='commissioning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_commissioning', to='projects.Steps', verbose_name='Comissionamento'),
        ),
        migrations.AddField(
            model_name='projects',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por'),
        ),
        migrations.AddField(
            model_name='projects',
            name='electric_point',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electric_points.ElectricPoints', verbose_name='Ponto Elétrico'),
        ),
        migrations.AddField(
            model_name='projects',
            name='energizing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_energizing', to='projects.Steps', verbose_name='Energização'),
        ),
        migrations.AddField(
            model_name='projects',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_installation', to='projects.Steps', verbose_name='Instalação'),
        ),
        migrations.AddField(
            model_name='projects',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_operation', to='projects.Steps', verbose_name='Operation'),
        ),
        migrations.AddField(
            model_name='projects',
            name='pendencies',
            field=models.ManyToManyField(blank=True, related_name='project_pendencies', to='projects.Pendencies', verbose_name='Pendências'),
        ),
        migrations.AddField(
            model_name='pendencies',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pendency_project', to='projects.Projects', verbose_name='Projeto'),
        ),
    ]
