# Generated by Django 2.2 on 2019-05-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendencies',
            name='pendencies_type',
            field=models.CharField(max_length=255, null=True, verbose_name='Tipo de pendência'),
        ),
        migrations.AlterField(
            model_name='pendencies',
            name='progress_status',
            field=models.CharField(choices=[('0', 'A instalar'), ('1', 'A energizar'), ('2', 'A comissionar'), ('3', 'A operar'), ('4', 'Concluído')], max_length=255, verbose_name='Etapa de referência'),
        ),
    ]
