# Generated by Django 2.2 on 2019-05-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190508_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendencies',
            old_name='pendencies_type',
            new_name='pendency_type',
        ),
    ]
