# Generated by Django 2.2 on 2019-05-08 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190508_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendencies',
            name='solved_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 8, 12, 7, 47, 596710), verbose_name='Solucionada em'),
            preserve_default=False,
        ),
    ]
