# Generated by Django 2.2 on 2019-05-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_pendencies_solved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendencies',
            name='solved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Solucionada em'),
        ),
    ]
