# Generated by Django 2.2 on 2019-05-08 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190508_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='commissioning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_commissioning', to='projects.Steps', verbose_name='Comissionamento'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='energizing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_energizing', to='projects.Steps', verbose_name='Energização'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_installation', to='projects.Steps', verbose_name='Instalação'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_operation', to='projects.Steps', verbose_name='Operation'),
        ),
    ]
