# Generated by Django 2.2 on 2019-05-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190508_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de conclusão'),
        ),
    ]
