# Generated by Django 2.2 on 2019-05-08 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20190508_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_installation', to='projects.Steps', verbose_name='Instalação'),
        ),
    ]
