# Generated by Django 2.2 on 2019-05-08 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20190508_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_project', to='projects.Projects', verbose_name='Projeto'),
        ),
    ]
