# Generated by Django 2.2 on 2019-05-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20190508_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='designing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_project', to='projects.Steps', verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='pendencies',
            name='progress_status',
            field=models.CharField(choices=[('0', 'A projetar'), ('1', 'A instalar'), ('2', 'A energizar'), ('3', 'A comissionar'), ('4', 'A operar'), ('5', 'Concluído')], max_length=255, verbose_name='Etapa de referência'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='progress_status',
            field=models.CharField(choices=[('0', 'A projetar'), ('1', 'A instalar'), ('2', 'A energizar'), ('3', 'A comissionar'), ('4', 'A operar'), ('5', 'Concluído')], default='0', max_length=255, verbose_name='Etapa de referência'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='progress_status',
            field=models.CharField(choices=[('0', 'A projetar'), ('1', 'A instalar'), ('2', 'A energizar'), ('3', 'A comissionar'), ('4', 'A operar'), ('5', 'Concluído')], max_length=255, verbose_name='Etapa de referência'),
        ),
    ]
