# Generated by Django 2.2 on 2019-05-10 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0019_steps_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='finished_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_finished_by', to=settings.AUTH_USER_MODEL, verbose_name='Encerrado por'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por'),
        ),
    ]
