# Generated by Django 2.2 on 2019-06-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20190510_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='sob',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Número do Projeto'),
        ),
    ]
