# Generated by Django 2.2 on 2019-06-05 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20190602_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='finished_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_finished_by', to=settings.AUTH_USER_MODEL, verbose_name='Encerrado por'),
        ),
    ]
