# Generated by Django 2.0.13 on 2019-07-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20190605_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='operative_number',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Numeração operativa'),
        ),
    ]
