# Generated by Django 2.0.13 on 2019-07-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_projects_operative_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='operative_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Numeração operativa'),
        ),
    ]
