# Generated by Django 2.2 on 2019-05-06 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Identificador')),
                ('key_amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade de chaves')),
                ('recloser_amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade de religadores')),
                ('set_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Conjunto')),
                ('electric_region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Região elétrica')),
            ],
            options={
                'verbose_name': 'Alimentador',
                'verbose_name_plural': 'Alimentadores',
                'db_table': 'feeder',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('city', models.CharField(choices=[('1', 'Abadia de Goiás'), ('2', 'Abadiânia'), ('3', 'Acreúna'), ('4', 'Adelândia'), ('5', 'Água Fria de Goiás'), ('6', 'Água Limpa'), ('7', 'Águas Lindas de Goiás'), ('8', 'Alexânia'), ('9', 'Aloândia'), ('10', 'Alto Horizonte\u200e'), ('11', 'Alto Paraíso de Goiás'), ('12', 'Alvorada do Norte'), ('13', 'Amaralina'), ('14', 'Americano do Brasil'), ('15', 'Amorinópolis'), ('16', 'Anápolis\u200e'), ('17', 'Anhanguera'), ('18', 'Anicuns'), ('19', 'Aparecida de Goiânia'), ('20', 'Aparecida do Rio Doce'), ('21', 'Aporé'), ('22', 'Araçu'), ('23', 'Aragarças'), ('24', 'Aragoiânia'), ('25', 'Araguapaz'), ('26', 'Arenópolis'), ('27', 'Aruanã'), ('28', 'Aurilândia'), ('29', 'Avelinópolis'), ('30', 'Baliza'), ('31', 'Barro Alto'), ('32', 'Bela Vista de Goiás'), ('33', 'Bom Jardim de Goiás'), ('34', 'Bom Jesus de Goiás'), ('35', 'Bonfinópolis'), ('36', 'Bonópolis'), ('37', 'Brazabrantes'), ('38', 'Britânia'), ('39', 'Buriti Alegre'), ('40', 'Buriti de Goiás'), ('41', 'Buritinópolis'), ('42', 'Cabeceiras'), ('43', 'Cachoeira Alta'), ('44', 'Cachoeira de Goiás'), ('45', 'Cachoeira Dourada'), ('46', 'Caçu'), ('47', 'Caiapônia'), ('48', 'Caldas Novas\u200e'), ('49', 'Caldazinha'), ('50', 'Campestre de Goiás'), ('51', 'Campinaçu'), ('52', 'Campinorte'), ('53', 'Campo Alegre de Goiás'), ('54', 'Campo Limpo de Goiás'), ('55', 'Campos Belos'), ('56', 'Campos Verdes'), ('57', 'Carmo do Rio Verde'), ('58', 'Castelândia'), ('59', 'Catalão'), ('60', 'Caturaí'), ('61', 'Cavalcante'), ('62', 'Ceres'), ('63', 'Cezarina'), ('64', 'Chapadão do Céu'), ('65', 'Cidade Ocidental\u200e'), ('66', 'Cocalzinho de Goiás'), ('67', 'Colinas do Sul'), ('68', 'Córrego do Ouro'), ('69', 'Corumbá de Goiás'), ('70', 'Corumbaíba'), ('71', 'Cristalina\u200e'), ('72', 'Cristianópolis'), ('73', 'Crixás'), ('74', 'Cromínia'), ('75', 'Cumari'), ('76', 'Damianópolis'), ('77', 'Damolândia'), ('78', 'Davinópolis'), ('79', 'Diorama'), ('80', 'Divinópolis de Goiás'), ('81', 'Doverlândia'), ('82', 'Edealina'), ('83', 'Edéia'), ('84', 'Estrela do Norte'), ('85', 'Faina'), ('86', 'Fazenda Nova'), ('87', 'Firminópolis'), ('88', 'Flores de Goiás'), ('89', 'Formosa'), ('90', 'Formoso'), ('91', 'Gameleira de Goiás'), ('92', 'Goianápolis'), ('93', 'Goiandira'), ('94', 'Goianésia'), ('95', 'Goiânia'), ('96', 'Goianira'), ('97', 'Goiás'), ('98', 'Goiatuba'), ('99', 'Gouvelândia'), ('100', 'Guapó\u200e'), ('101', 'Guaraíta'), ('102', 'Guarani de Goiás\u200e'), ('103', 'Guarinos'), ('104', 'Heitoraí'), ('105', 'Hidrolândia'), ('106', 'Hidrolina'), ('107', 'Iaciara'), ('108', 'Inaciolândia'), ('109', 'Indiara'), ('110', 'Inhumas'), ('111', 'Ipameri\u200e'), ('112', 'Ipiranga de Goiás'), ('113', 'Iporá\u200e'), ('114', 'Israelândia'), ('115', 'Itaberaí'), ('116', 'Itaguari'), ('117', 'Itaguaru'), ('118', 'Itajá'), ('119', 'Itapaci'), ('120', 'Itapirapuã'), ('121', 'Itapuranga'), ('122', 'Itarumã'), ('123', 'Itauçu'), ('124', 'Itumbiara\u200e'), ('125', 'Ivolândia'), ('126', 'Jamil'), ('127', 'Jandaia'), ('128', 'Jaraguá'), ('129', 'Jataí'), ('130', 'Jaupaci'), ('131', 'Jesúpolis'), ('132', 'Joviânia'), ('133', 'Jussara'), ('134', 'Lagoa Santa'), ('135', 'Leopoldo de Bulhões'), ('136', 'Luziânia\u200e'), ('137', 'Mairipotaba'), ('138', 'Mambaí'), ('139', 'Mambaí'), ('140', 'Mara Rosa'), ('141', 'Mara Rosa\u200e'), ('142', 'Marzagão'), ('143', 'Matrinchã'), ('144', 'Maurilândia'), ('145', 'Mimoso de Goiás'), ('146', 'Minaçu'), ('147', 'Mineiros'), ('148', 'Moiporá'), ('149', 'Monte Alegre de Goiás'), ('150', 'Montes Claros de Goiás'), ('151', 'Montividiu'), ('152', 'Montividiu do Norte'), ('153', 'Morrinhos'), ('154', 'Morro Agudo de Goiás'), ('155', 'Mossâmedes'), ('156', 'Mozarlândia'), ('157', 'Mundo Novo'), ('158', 'Mutunópolis'), ('159', 'Nazário'), ('160', 'Nerópolis'), ('161', 'Niquelândia'), ('162', 'Nova América'), ('163', 'Nova Aurora'), ('164', 'Nova Crixás'), ('165', 'Nova Glória'), ('166', 'Nova Iguaçu de Goiás'), ('167', 'Nova Roma'), ('168', 'Nova Veneza'), ('169', 'Novo Brasil'), ('170', 'Novo Gama'), ('171', 'Novo Planalto'), ('172', 'Orizona'), ('173', 'Ouro Verde de Goiás'), ('174', 'Ouvidor'), ('175', 'Padre Bernardo'), ('176', 'Palestina de Goiás'), ('177', 'Palmeiras de Goiás'), ('178', 'Palmelo'), ('179', 'Palminópolis'), ('180', 'Palminópolis\u200e'), ('181', 'Panamá'), ('182', 'Paranaiguara'), ('183', 'Paraúna'), ('184', 'Perolândia'), ('185', 'Petrolina de Goiás'), ('186', 'Pilar de Goiás'), ('187', 'Piracanjuba'), ('188', 'Piranhas'), ('189', 'Pirenópolis\u200e'), ('190', 'Pires do Rio'), ('191', 'Planaltina'), ('192', 'Pontalina'), ('193', 'Porangatu\u200e'), ('194', 'Porteirão'), ('195', 'Portelândia'), ('196', 'Posse'), ('197', 'Professor Jamil'), ('198', 'Quirinópolis\u200e'), ('199', 'Rialma'), ('200', 'Rianápolis'), ('201', 'Rio Quente'), ('202', 'Rio Verde\u200e'), ('203', 'Rubiataba'), ('204', 'Sanclerlândia'), ('205', 'Santa Bárbara de Goiás'), ('206', 'Santa Cruz de Goiás'), ('207', 'Santa Fé de Goiás'), ('208', 'Santa Helena de Goiás'), ('209', 'Santa Isabel'), ('210', 'Santa Rita do Araguaia'), ('211', 'Santa Rita do Novo Destino'), ('212', 'Santa Rosa de Goiás'), ('213', 'Santa Tereza de Goiás'), ('214', 'Santa Terezinha de Goiás'), ('215', 'Santo Antônio da Barra'), ('216', 'Santo Antônio de Goiás'), ('217', 'Santo Antônio do Descoberto'), ('218', 'São Domingos'), ('219', 'São Francisco de Goiás'), ('220', 'São João da Paraúna'), ('221', "São João d'Aliança"), ('222', 'São Luís de Montes Belos'), ('223', 'São Luiz do Norte'), ('224', 'São Miguel do Araguaia'), ('225', 'São Miguel do Passa-Quatro'), ('226', 'São Patrício'), ('227', 'São Simão'), ('228', 'Senador Canedo'), ('229', 'Serranópolis'), ('230', 'Silvânia'), ('231', 'Simolândia'), ('232', "Sítio d'Abadia"), ('233', 'Taquaral de Goiás'), ('234', 'Teresina de Goiás'), ('235', 'Terezópolis de Goiás'), ('236', 'Três Ranchos'), ('237', 'Trindade'), ('238', 'Trombas'), ('239', 'Turvânia'), ('240', 'Turvelândia'), ('241', 'Uirapuru'), ('242', 'Uruaçu'), ('243', 'Uruana'), ('244', 'Urutaí'), ('245', 'Valparaíso de Goiás'), ('246', 'Varjão'), ('247', 'Vianópolis'), ('248', 'Vicentinópolis'), ('249', 'Vila Boa'), ('250', 'Vila Propício')], max_length=255, null=True, verbose_name='Estado')),
                ('state', models.CharField(choices=[('GO', 'Goiás')], max_length=255, null=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('obsolete', models.BooleanField(default=False, null=True, verbose_name='Posição obsoleta')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
                'db_table': 'locations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ElectricPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True, verbose_name='Identificador único')),
                ('equipment_type', models.CharField(choices=[('0', 'Chave'), ('1', 'Religador')], max_length=255, null=True, verbose_name='Tipo de equipamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
                ('feeder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='electric_points.Feeders', verbose_name='Alimentador')),
                ('locations', models.ManyToManyField(blank=True, to='electric_points.Locations', verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Ponto Elétrico',
                'verbose_name_plural': 'Pontos Elétricos',
                'db_table': 'electric_points',
            },
        ),
    ]
