# Generated by Django 2.2 on 2019-05-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='progress_status',
            field=models.CharField(choices=[('0', 'A instalar'), ('1', 'A energizar'), ('2', 'A comissionar'), ('3', 'A operar'), ('4', 'Concluído')], default=0, max_length=255, verbose_name='Etapa de referência'),
            preserve_default=False,
        ),
    ]
