# Generated by Django 2.2 on 2019-05-08 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electric_points', '0002_locations_progress_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageStudies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(max_length=255, null=True, verbose_name='Tipo de comunicação')),
                ('communication_detail', models.CharField(max_length=255, null=True, verbose_name='Descrição para o tipo de comunicação')),
                ('electric_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electric_points.ElectricPoints', verbose_name='Ponto Elétrico')),
            ],
            options={
                'verbose_name': 'Estudo Teórico de Cobertura',
                'verbose_name_plural': 'Estudos Teóricos de Cobertura',
                'db_table': 'coverage_studies',
            },
        ),
        migrations.CreateModel(
            name='MobileNetworkSignals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(choices=[('0', 'Claro'), ('1', 'Oi'), ('2', 'Tim'), ('3', 'Vivo')], max_length=255, null=True, verbose_name='Operadora')),
                ('mobile_signal', models.CharField(max_length=255, null=True, verbose_name='Sinal')),
                ('coverage_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electric_points.CoverageStudies', verbose_name='Estudo Teórico de Cobertura')),
            ],
            options={
                'verbose_name': 'Sinal de Rede Móvel',
                'verbose_name_plural': 'Sinais de Redes Móveis',
                'db_table': 'mobile_network_signals',
            },
        ),
        migrations.AddField(
            model_name='coveragestudies',
            name='mobile_signals',
            field=models.ManyToManyField(blank=True, to='electric_points.MobileNetworkSignals', verbose_name='Redes Móveis'),
        ),
    ]
