# Generated by Django 2.2 on 2019-05-09 17:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electric_points', '0003_auto_20190508_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragestudies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 5, 9, 17, 12, 3, 351018, tzinfo=utc), verbose_name='Cadastrado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coveragestudies',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='progress_status',
            field=models.CharField(choices=[('0', 'A projetar'), ('1', 'A instalar'), ('2', 'A energizar'), ('3', 'A comissionar'), ('4', 'A operar'), ('5', 'Concluído')], max_length=255, verbose_name='Etapa de referência'),
        ),
    ]
