# Generated by Django 2.2 on 2019-05-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_points', '0004_auto_20190509_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveragestudies',
            name='communication_detail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição para o tipo de comunicação'),
        ),
    ]
