# Generated by Django 2.2 on 2019-05-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_points', '0005_auto_20190509_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveragestudies',
            name='communication_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de comunicação'),
        ),
    ]
