# Generated by Django 2.2 on 2019-05-10 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electric_points', '0006_auto_20190509_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coveragestudies',
            name='mobile_signals',
        ),
        migrations.AddField(
            model_name='coveragestudies',
            name='company_name',
            field=models.CharField(blank=True, choices=[('0', 'Claro'), ('1', 'Oi'), ('2', 'Tim'), ('3', 'Vivo')], max_length=255, null=True, verbose_name='Operadora'),
        ),
        migrations.AddField(
            model_name='coveragestudies',
            name='mobile_signal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sinal'),
        ),
        migrations.AlterField(
            model_name='coveragestudies',
            name='electric_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='electric_points.ElectricPoints', verbose_name='Ponto Elétrico'),
        ),
        migrations.DeleteModel(
            name='MobileNetworkSignals',
        ),
    ]
