# Generated by Django 2.2 on 2019-05-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electric_points', '0007_auto_20190510_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coveragestudies',
            name='communication_detail',
        ),
    ]
