# Generated by Django 2.2 on 2019-05-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_points', '0008_remove_coveragestudies_communication_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='related_electric_point_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ponto Elétrico'),
        ),
    ]
