# Generated by Django 2.2 on 2019-05-12 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electric_points', '0009_locations_related_electric_point_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de equipamento')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código do Equipamento')),
                ('serial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de série')),
                ('internet_protocol_one', models.CharField(blank=True, max_length=255, null=True, verbose_name='IP Primário')),
                ('port_one', models.CharField(blank=True, max_length=255, null=True, verbose_name='Porta Primária')),
                ('internet_protocol_two', models.CharField(blank=True, max_length=255, null=True, verbose_name='IP Secundário')),
                ('port_two', models.CharField(blank=True, max_length=255, null=True, verbose_name='Porta Secundária')),
                ('electric_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='electric_points.ElectricPoints', verbose_name='Ponto Elétrico')),
            ],
            options={
                'verbose_name': 'Liberação de Materiais de Telecom',
                'verbose_name_plural': 'Liberações de Materiais de Telecom',
                'db_table': 'telecom_supply_delivery',
            },
        ),
    ]
