# Generated by Django 2.2 on 2019-05-12 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_points', '0010_supplydelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveragestudies',
            name='mobile_signal',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Sinal'),
        ),
        migrations.AlterField(
            model_name='supplydelivery',
            name='internet_protocol_one',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='IP Primário'),
        ),
        migrations.AlterField(
            model_name='supplydelivery',
            name='internet_protocol_two',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='IP Secundário'),
        ),
        migrations.AlterField(
            model_name='supplydelivery',
            name='port_one',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True, verbose_name='Porta Primária'),
        ),
        migrations.AlterField(
            model_name='supplydelivery',
            name='port_two',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True, verbose_name='Porta Secundária'),
        ),
    ]
