# Generated by Django 2.2 on 2019-05-12 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_points', '0011_auto_20190512_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplydelivery',
            name='equipment_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Equipamento'),
        ),
        migrations.AlterField(
            model_name='supplydelivery',
            name='port_one',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Porta Primária'),
        ),
        migrations.AlterField(
            model_name='supplydelivery',
            name='port_two',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Porta Secundária'),
        ),
    ]
