# Generated by Django 2.2 on 2019-05-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_points', '0012_auto_20190512_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplydelivery',
            name='serial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de Série'),
        ),
    ]
