# Generated by Django 2.2 on 2019-05-12 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electric_points', '0013_auto_20190512_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplydelivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Cadastrado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplydelivery',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por'),
        ),
    ]
