# Generated by Django 2.2 on 2019-05-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_points', '0014_auto_20190512_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplydelivery',
            name='communication_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Comunicação'),
        ),
    ]
