# Generated by Django 2.2 on 2019-05-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electric_points', '0015_supplydelivery_communication_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplydelivery',
            old_name='created_at',
            new_name='created_at_x',
        ),
    ]
