# Generated by Django 2.2 on 2019-05-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electric_points', '0016_auto_20190513_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplydelivery',
            old_name='created_at_x',
            new_name='created_at',
        ),
    ]
