# Generated by Django 2.2 on 2019-05-13 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electric_points', '0017_auto_20190513_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeederStudies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_adjustment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ajuste de Fase')),
                ('neutral_adjustment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ajuste de Neutro')),
                ('sensitive_neutral_adjustment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ajuste de Neutro Sensível')),
                ('shots', models.IntegerField(blank=True, null=True, verbose_name='Número de Disparos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('applied', models.BooleanField(default=False, null=True, verbose_name='Implementado')),
                ('applied_at', models.DateTimeField(verbose_name='Implementado em')),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeder_study_applied_by', to=settings.AUTH_USER_MODEL, verbose_name='Implementado por')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeder_study_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
                ('electric_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='electric_points.ElectricPoints', verbose_name='Ponto Elétrico')),
            ],
            options={
                'verbose_name': 'Estudo de Alimentador',
                'verbose_name_plural': 'Estudos de Alimentadores',
                'db_table': 'feeder_studies',
            },
        ),
    ]
