# Generated by Django 2.2 on 2019-05-13 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electric_points', '0018_feederstudies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feederstudies',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Implementado em'),
        ),
        migrations.AlterField(
            model_name='feederstudies',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeder_study_applied_by', to=settings.AUTH_USER_MODEL, verbose_name='Implementado por'),
        ),
    ]
