# Generated by Django 2.2 on 2019-05-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_points', '0019_auto_20190513_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='related_electric_point_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ponto Elétrico obsoleto'),
        ),
    ]
