# Generated by Django 2.2 on 2019-05-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electric_points', '0020_auto_20190513_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricpoints',
            options={'ordering': ['created_at'], 'verbose_name': 'Ponto Elétrico', 'verbose_name_plural': 'Pontos Elétricos'},
        ),
    ]
