# Generated by Django 2.2 on 2019-06-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_points', '0021_auto_20190514_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricpoints',
            options={'ordering': ['created_at'], 'verbose_name': 'Posto Elétrico', 'verbose_name_plural': 'Postos Elétricos'},
        ),
        migrations.AlterField(
            model_name='locations',
            name='progress_status',
            field=models.CharField(choices=[('0', 'A projetar'), ('1', 'A instalar'), ('2', 'A energizar'), ('3', 'A comissionar'), ('4', 'A operar'), ('5', 'Concluído')], default='0', max_length=255, verbose_name='Etapa de referência'),
        ),
    ]
