# Generated by Django 2.0.13 on 2019-06-18 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electric_points', '0023_auto_20190602_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricpoints',
            options={'ordering': ['created_at'], 'verbose_name': 'Ponto Telecontrole', 'verbose_name_plural': 'Pontos Telecontroles'},
        ),
        migrations.AlterModelOptions(
            name='feederstudies',
            options={'verbose_name': 'Estudo de Proteção', 'verbose_name_plural': 'Estudos de Proteção'},
        ),
        migrations.AlterField(
            model_name='coveragestudies',
            name='electric_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='electric_points.ElectricPoints', verbose_name='Ponto Telecontrole'),
        ),
        migrations.AlterField(
            model_name='feederstudies',
            name='applied',
            field=models.BooleanField(default=False, verbose_name='Implementado'),
        ),
        migrations.AlterField(
            model_name='feederstudies',
            name='electric_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='electric_points.ElectricPoints', verbose_name='Ponto Telecontrole'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='obsolete',
            field=models.BooleanField(default=False, verbose_name='Posição obsoleta'),
        ),
        migrations.AlterField(
            model_name='supplydelivery',
            name='electric_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='electric_points.ElectricPoints', verbose_name='Ponto Telecontrole'),
        ),
    ]
