# Generated by Django 2.2 on 2019-05-06 21:05

import accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='static/img/avatars/default.jpg', upload_to=accounts.models.user_directory_path, verbose_name='Avatar')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatares',
                'db_table': 'avatars',
            },
        ),
        migrations.CreateModel(
            name='BasicUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='Primeiro nome')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Último nome')),
                ('username', models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='Usuário Enel')),
                ('profile', models.CharField(choices=[('0', 'Administrador'), ('1', 'Planejamento'), ('2', 'Execução'), ('3', 'Obras'), ('4', 'Telecontrole'), ('5', 'Telecom'), ('6', 'Proteção'), ('7', 'Visualização')], max_length=255, verbose_name='Perfil')),
                ('superuser', models.BooleanField(default=False, verbose_name='Administrador')),
                ('avatars', models.ManyToManyField(blank=True, to='accounts.Avatars', verbose_name='Avatar')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'Users',
            },
        ),
    ]
