# Generated by Django 2.2 on 2019-05-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='profile',
            field=models.CharField(choices=[('0', 'Administrador'), ('1', 'Planejamento'), ('2', 'Obras'), ('3', 'Telecontrole'), ('4', 'Telecom'), ('5', 'Proteção'), ('6', 'Visualização')], max_length=255, verbose_name='Perfil'),
        ),
    ]
