# Generated by Django 2.2 on 2019-05-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190508_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='profile',
            field=models.CharField(choices=[('0', 'Administração'), ('1', 'Planejamento'), ('2', 'Projeto'), ('3', 'Obras'), ('4', 'Telecontrole'), ('5', 'Telecom'), ('6', 'Proteção'), ('7', 'Visualização')], max_length=255, verbose_name='Perfil'),
        ),
    ]
